name: RainbondSpider

on:
  push:
    branches:
      - master

jobs:
  run-docker-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Docker Command
        run: |
          docker run --name rainbondspider \
          -e HOST=${{ secrets.HOST }} \
          -e PORT=${{ secrets.PORT }} \
          -e USER=${{ secrets.USER }} \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e DATABASE=${{ secrets.DATABASE }} \
          -e MARKETURL=${{ secrets.MARKETURL }} \
          -e MARKETID=${{ secrets.MARKETID }} \
          -e CHARTURL=${{ secrets.CHARTURL }} \
          ${{ secrets.IMAGES }}
